version: "3.8"

services:
  backend:
    image: ${ECR_URI}/tasktracker-backend:${BRANCH}
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    image: ${ECR_URI}/tasktracker-frontend:${BRANCH}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
