version: '3.8'

services:
  backend:
    image: 600748199143.dkr.ecr.us-east-1.amazonaws.com/tasktracker-backend:latest
    ports:
      - "5000:5000"
    restart: always
    environment:
      - NODE_ENV=main
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: 600748199143.dkr.ecr.us-east-1.amazonaws.com/tasktracker-frontend:latest
    ports:
      - "80:3000"
    restart: always
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
