global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'task-tracker-backend'
    static_configs:
      - targets: ['<BACKEND_PRIVATE_IP>:5000']  # Customize based on your EC2 or container IP

  - job_name: 'task-tracker-frontend'
    static_configs:
      - targets: ['<FRONTEND_PRIVATE_IP>:80']  # Optional: if your frontend exposes metrics
