name: Deploy App to EC2 (Frontend & Backend)

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        # If your secret is base64-encoded, use base64 -d. If not, remove | base64 -d
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2 (based on branch)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          EC2_IP: ${{ github.ref == 'refs/heads/main' && secrets.PROD_EC2_PUBLIC_IP || secrets.STAGING_EC2_PUBLIC_IP }}
          ENV_FOLDER: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
        run: |
          set -e
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@$EC2_IP << 'EOF'
            set -e
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
            docker-compose -f docker-compose.$ENVIRONMENT.yml pull
            docker-compose -f docker-compose.$ENVIRONMENT.yml up -d
            docker system prune -af
            docker ps
          EOF