name: Deploy App to EC2 (Frontend & Backend)

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        # If your secret is base64-encoded, use base64 -d. If not, remove | base64 -d
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2 (based on branch)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          EC2_IP: ${{ github.ref == 'refs/heads/main' && secrets.PROD_EC2_PUBLIC_IP || secrets.STAGING_EC2_PUBLIC_IP }}
          ENV_FOLDER: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
        run: |
          set -e
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@$EC2_IP << 'EOF'
            set -e
            echo "[+] Installing AWS CLI if needed..."
            if ! command -v aws &> /dev/null; then
              sudo apt update && sudo apt install -y awscli
            fi

            echo "[+] Configuring AWS credentials..."
            mkdir -p ~/.aws
            cat <<EOT > ~/.aws/credentials
[default]
aws_access_key_id=${AWS_ACCESS_KEY_ID}
aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
region=us-east-1
EOT

            echo "[+] Deploying Backend..."
            cd /home/ubuntu/$ENV_FOLDER/backend
            git pull origin $ENV_FOLDER || git pull origin main || git pull origin staging
            docker-compose down
            docker-compose up -d --build

            echo "[+] Deploying Frontend..."
            cd /home/ubuntu/$ENV_FOLDER/frontend
            git pull origin $ENV_FOLDER || git pull origin main || git pull origin staging
            docker-compose down
            docker-compose up -d --build

            echo "[✔] Deployment complete for $ENV_FOLDER."
          EOF

      - name: Notify Deployment Success
        if: success()
        run: echo "✅ Deployment to ${{ env.ENV_FOLDER }} succeeded!"

      - name: Notify Deployment Failure
        if: failure()
        run: echo "❌ Deployment to ${{ env.ENV_FOLDER }} failed!"