name: CI/CD Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - prod
      app:
        description: 'App to deploy'
        required: true
        default: 'frontend'
        type: choice
        options:
          - frontend
          - backend

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set Host Variable
        id: sethost
        run: |
          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            echo "HOST=${{ secrets.EC2_HOST_PROD }}" >> $GITHUB_ENV
          else
            echo "HOST=${{ secrets.EC2_HOST_STAGING }}" >> $GITHUB_ENV
          fi

      - name: Deploy App
        env:
          HOST: ${{ env.HOST }}
          KEY: id_rsa
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh "${{ github.event.inputs.environment }}" "${{ github.event.inputs.app }}"
